version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.1
        environment:
          CC_TEST_REPORTER_ID: 9f8a5da723397006023534dc6c5e32fc95d38bf7a92ae0e43530dba2a726722e
    steps:
      - checkout
      - run: 
          command: |
            sudo apt install python-pip
            sudo pip install -U pip pipenv
      - run:
          command: |
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
            chmod +x ./cc-test-reporter
      - run:
          command: |
            pipenv --python python3.6
            pipenv install --dev
      - run:
          command: |
            pipenv run pytest
            ./cc-test-reporter format-coverage coverage/coverage.xml -t coverage.py
            ./cc-test-reporter upload-coverage
      - run:
          command: |
            ./cc-test-reporter before-build
      - run:
          command: |
            pipenv run pytest
      - run:
          command: |
            pipenv run flake8
      - run:
         command: |
            pipenv run safety check
      - store_artifacts:
          path: htmlcov
          destination: htmlcov
          